export default {
    base: [
        {color: '#9A2A2D', fontColor: '#FFF', level: '1', title: 'Charge!', text: '+1 Strength in battle when attacking.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '1', title: 'Charge!', text: '+1 Strength in battle when attacking.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '1', title: 'Stargate', text: 'When you use a movement action, you may teleport for -1pp.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '1', title: 'God Speed', text: '+1 Strength in battle when attacking.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '2', title: 'Carnage', text: 'In battle, all your troops gain +1 damage.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '2', title: 'Offensive Strategy', text: 'Take back your discarded battle cards. Replace one of them with the special +3 Strength / 3 Damage.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '2', title: 'Open Gates', text: 'All of your troops ignore the effect of walls.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '2', title: 'Teleport', text: 'When you use a movement action, you can teleport your troops from an obelisk.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '3', title: 'Royal Scarab', text: 'For the linked troop: +2 Movement capacity, +2 Strength.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '3', title: 'Blades of Neith', text: 'In all battles, all your troops have +1 Strength.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '3', title: 'Divine Wound', text: 'In battle, after cards are revealed, add +1 Strength for each DI card you discard.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '3', title: 'Victory Point', text: '1 Victory Point'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '4', title: 'Giant Scorpion', text: 'For the linked troop: +1 Movement capacity, +2 Strength, +2 Damage.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '4', title: 'Initiative', text: 'When you are attacking, destroy 2 units from the target troop before the beginning of the battle.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '4', title: 'Phoenix', text: 'For the linked troop: +1 Movement capacity, +2 Strength. The troop ignores the effects of walls.'},
        {color: '#9A2A2D', fontColor: '#FFF', level: '4', title: 'Act of God', text: 'Take an additional silver Action token, to be placed and played at the same time as a regular token.'},

        {color: '#184A7C', fontColor: '#FFF', level: '1', title: 'Recruiting Scribe', text: 'The recruit action gives you 2 more units.'},
        {color: '#184A7C', fontColor: '#FFF', level: '1', title: 'Recruiting Scribe', text: 'The recruit action gives you 2 more units.'},
        {color: '#184A7C', fontColor: '#FFF', level: '1', title: 'Defense!', text: 'You gain +1 Strength in battle when defending.'},
        {color: '#184A7C', fontColor: '#FFF', level: '1', title: 'Defense!', text: 'You gain +1 Strength in battle when defending.'},
        {color: '#184A7C', fontColor: '#FFF', level: '2', title: 'Legion', text: 'Your troops may now contain a maximum of 7 units instead of 5.'},
        {color: '#184A7C', fontColor: '#FFF', level: '2', title: 'Ancestral Elephant', text: 'For the linked troop: +1 Movement capacity, +1 Strength, +1 Protection.'},
        {color: '#184A7C', fontColor: '#FFF', level: '2', title: 'Defensive Strategy', text: 'Take back your discarded battle cards. Replace one of them with the special +3 Strenth / 3 Protection.'},
        {color: '#184A7C', fontColor: '#FFF', level: '2', title: 'Deep Desert Snake', text: 'For the linked troop: +1 Movement capacity. Cancel any other creature effect in battle.'},
        {color: '#184A7C', fontColor: '#FFF', level: '3', title: 'Shield of Neith', text: 'In battle, all your troops gain +1 Protection.'},
        {color: '#184A7C', fontColor: '#FFF', level: '3', title: 'Defensive Victory', text: 'If you win a battle as the defender, you also gain a Victory Point.'},
        {color: '#184A7C', fontColor: '#FFF', level: '3', title: 'Prescience', text: 'In battle, your opponent must show you his battle card before you play yours.'},
        {color: '#184A7C', fontColor: '#FFF', level: '3', title: 'Victory Point', text: '1 Victory Point'},
        {color: '#184A7C', fontColor: '#FFF', level: '4', title: 'Reinforcements', text: 'During the Night phase you may add 4 units to a troop and/or your city.'},
        {color: '#184A7C', fontColor: '#FFF', level: '4', title: 'Sphinx', text: 'For the linked troop: +2 Strength, 1 Victory Point.'},
        {color: '#184A7C', fontColor: '#FFF', level: '4', title: 'Divine Will', text: 'Take the golden Action token. It must be played at the same time as a regular token but on the top level space, as a Move or Recruit action.'},
        {color: '#184A7C', fontColor: '#FFF', level: '4', title: 'Act of God', text: 'Take an additional silver Action token, to be placed and played at the same time as a regular token.'},

        {color: '#FFFFFF', fontColor: '#000', level: '1', title: 'Priest', text: 'When you use the pray action, you can +1pp.'},
        {color: '#FFFFFF', fontColor: '#000', level: '1', title: 'Priest', text: 'When you use the pray action, you can +1pp.'},
        {color: '#FFFFFF', fontColor: '#000', level: '1', title: 'Priestess', text: 'When you buy a power tile, its cost is -1pp.'},
        {color: '#FFFFFF', fontColor: '#000', level: '1', title: 'Priestess', text: 'When you buy a power tile, its cost is -1pp.'},
        {color: '#FFFFFF', fontColor: '#000', level: '2', title: 'Slaves', text: 'When using the raising pyramid action, each level costs -1pp.'},
        {color: '#FFFFFF', fontColor: '#000', level: '2', title: 'High Priest', text: 'During the Night phase you gain 2 additional pp in the pp distribution.'},
        {color: '#FFFFFF', fontColor: '#000', level: '2', title: 'Crusade', text: 'Gain 2pp for each unit you destroy in battle.'},
        {color: '#FFFFFF', fontColor: '#000', level: '2', title: 'Divine Boon', text: 'During the Night phase take an additional DI card when they are distributed.'},
        {color: '#FFFFFF', fontColor: '#000', level: '3', title: 'Hand of God', text: 'During the Night phase you may raise a pyramid by 1 level for free.'},
        {color: '#FFFFFF', fontColor: '#000', level: '3', title: 'Vision', text: 'During the Night phase when you pick a DI card, draw 5 and keep 1 of your choice.'},
        {color: '#FFFFFF', fontColor: '#000', level: '3', title: 'Holy War', text: 'Gain 4pp for each battle you win (attack or defense).'},
        {color: '#FFFFFF', fontColor: '#000', level: '3', title: 'Victory Point', text: '1 Victory Point.'},
        {color: '#FFFFFF', fontColor: '#000', level: '4', title: 'Priest of Ra', text: 'When you spend pp, each cost is reduced by 1.'},
        {color: '#FFFFFF', fontColor: '#000', level: '4', title: 'Priest of Amon', text: 'During the Night phase you gain 5 additional pp in the pp distribution.'},
        {color: '#FFFFFF', fontColor: '#000', level: '4', title: 'The Mummy', text: 'For the linked troop: +1 Movement capacity, +2 Strength, +1 DI Card (during Night phase).'},
        {color: '#FFFFFF', fontColor: '#000', level: '4', title: 'Act of God', text: 'Take an additional silver Action token, to be placed and played at the same time as a regular token.'}
    ],
    blackPyramid: [
        {color: '#000000', fontColor: '#FFF', level: '1', title: 'Mercenaries', text: 'When you buy this tile, place the 3 male mercenaries in your city. They are basic units. The same player cannot buy the 2 Mercenaries tiles.'},
        {color: '#000000', fontColor: '#FFF', level: '1', title: 'Mercenaries', text: 'When you buy this tile, place the 3 female mercenaries in your city. They are basic units. The same player cannot buy the 2 Mercenaries tiles.'},
        {color: '#000000', fontColor: '#FFF', level: '1', title: 'Enforced Recruitment', text: 'During the recruit action, you can place the recruited units on any space(s) where you already have troops or your city.'},
        {color: '#000000', fontColor: '#FFF', level: '1', title: 'Dark Ritual', text: 'Take the golden Action token. It must be played at the same time as a regular token but on the top level space, as a Pray action.'},
        {color: '#000000', fontColor: '#FFF', level: '2', title: 'Honor in Battle', text: 'Gain 1pp for each of your units destroyed by your opponent in battle (at the end of battle).'},
        {color: '#000000', fontColor: '#FFF', level: '2', title: 'Dedication to Battle', text: 'During move/attack action gain 2pp if you move into a space with an enemy troop (even if there is no battle).'},
        {color: '#000000', fontColor: '#FFF', level: '2', title: "Khnum's Sphinx", text: "For the linked troop: +1 Movement, +1 Strength. To move into sphinx's space, opponent must pay 2pp"},
        {color: '#000000', fontColor: '#FFF', level: '2', title: 'Twin Ceremony', text: 'Take the golden Action token. You can reuse a buy action that you already used this turn by paying an extra 1pp.'},
        {color: '#000000', fontColor: '#FFF', level: '3', title: 'Griffin Sphinx', text: 'Linked troop: +2 Strength. When using a move/attack action, the troop can teleport from an obelisk (costs equal to teleportation cost).'},
        {color: '#000000', fontColor: '#FFF', level: '3', title: 'Forced March', text: 'Take the golden Action token. It must be played at the same time as a regular token but on the top level space, as a move/attack action.'},
        {color: '#000000', fontColor: '#FFF', level: '3', title: 'Deadly Trap', text: 'When an opposing troop moves into a space occupied by one of yours, your opponent destroys one of his units before the battle starts.'},
        {color: '#000000', fontColor: '#FFF', level: '3', title: 'Victory Point', text: '1 Victory Point.'},
        {color: '#000000', fontColor: '#FFF', level: '4', title: 'Devourer', text: 'Linked troop: +1 Movement, +2 Strength; no non-battle damage. After a battle win, if you destroyed 2 opposing units, gain +1 Battle VP.'},
        {color: '#000000', fontColor: '#FFF', level: '4', title: 'Bestial Fury', text: 'Every troop you control: +1 Movement capacity, +1 Strength and +1 Damage.'},
        {color: '#000000', fontColor: '#FFF', level: '4', title: 'Divine Strength', text: 'Every time you gain at least 1pp during the Day phase, gain 1 extra pp.'},
        {color: '#000000', fontColor: '#FFF', level: '4', title: 'Act of God', text: 'Take an additional silver Action token, to be placed and played at the same time as a regular token.'}
    ]
}
